server:
  port: 9000
  servlet:    context-path: /day02_springboot
spring:  mvc:    view:      prefix: /jsp/
      suffix: .jsp
# 连接池的配置
  datasource: 
        type: com.alibaba.druid.pool.DruidDataSource 
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis的有关配置 
mybatis:
  # mapper配置文件所在的路径
  mapper-locations: classpath:mapper/*Mapper.xml
  # 别名
  type-aliases-package: com.qrsx.day02_springboot.pojo
 
#showSql 暂时不管
logging:
  level:
    com:
      example:
        mapper : debug   